#ifndef SCBINUTIL_UTILS_H_
#define SCBINUTIL_UTILS_H_

#include <cstdint>
#include <span>

namespace scbinutil {

/// Seeks the binary section within the file contents \p file
/// This function strips the prepended bash script off of the executable file
/// generated by the compiler.
/// See documentation of `writeBashHeader()` in scatha-c for an explanation of
/// the convention
std::span<uint8_t const> seekBinary(std::span<uint8_t const> file);

} // namespace scbinutil

#endif // SCBINUTIL_UTILS_H_
