#ifndef SVM_UTIL_H_
#define SVM_UTIL_H_

#include <span>
#include <string_view>
#include <vector>

#include <svm/Common.h>

namespace svm {

class VirtualMachine;

/// Seeks the binary section within the file contents \p file
/// This function strips the prepended bash script off of the executable file
/// generated by the compiler.
/// See documentation of `writeBashHeader()` in scatha-c for an explanation of
/// the convention
std::span<uint8_t const> seekBinary(std::span<uint8_t const> file);

///
std::vector<uint8_t> readBinaryFromFile(std::string_view path);

/// Copys arguments onto the stack below the stack frame of `main()`
std::array<u64, 2> setupArguments(VirtualMachine& vm,
                                  std::span<std::string const> arguments);

} // namespace svm

#endif // SVM_UTIL_H_
