
function(SCSetCompilerOptions target)
  if(NOT SCATHA_DEV_MODE)
    return()
  endif()

  if (WIN32)
    if (MSVC)
      target_compile_options(${target} PRIVATE "/W3")
      target_compile_options(${target} PRIVATE "/WX")
      target_compile_options(${target} PRIVATE "/D_CRT_SECURE_NO_WARNINGS")
      target_compile_options(${target} PRIVATE "/MP")
      target_compile_definitions(${target} PRIVATE SC_APIEXPORT)
    endif()
  else()
    target_compile_options(${target} PRIVATE "-Wall")
    target_compile_options(${target} PRIVATE "-Wextra")
    target_compile_options(${target} PRIVATE "-pedantic")

    target_compile_options(${target} PRIVATE "-Wdeprecated")
    target_compile_options(${target} PRIVATE "-Wmissing-declarations")
    target_compile_options(${target} PRIVATE "-Wnon-virtual-dtor")
    target_compile_options(${target} PRIVATE "-Wnull-dereference")
    target_compile_options(${target} PRIVATE "-Woverloaded-virtual")
    # We enable this later, this triggers too often
    #target_compile_options(${target} PRIVATE "-Wshadow")
    target_compile_options(${target} PRIVATE "-Wunused")
  endif()
endfunction()

if(SCATHA_DEV_MODE)
  if(NOT MSVC)
    add_compile_options("$<$<CONFIG:Debug>:-fsanitize=address>")
    add_link_options("$<$<CONFIG:Debug>:-fsanitize=address>")
    add_compile_options("$<$<CONFIG:Debug>:-fsanitize=undefined>")
    add_link_options("$<$<CONFIG:Debug>:-fsanitize=undefined>")
  endif()
endif()
