
set(scatha_headers
  include/scatha/AST/Fwd.h
  include/scatha/AST/Lists.def.h
  include/scatha/AST/Print.h

  include/scatha/Assembly/Assembler.h
  include/scatha/Assembly/AssemblyStream.h
  include/scatha/Assembly/Fwd.h
  include/scatha/Assembly/Options.h

  include/scatha/CodeGen/CodeGen.h
  include/scatha/CodeGen/Logger.h
  include/scatha/CodeGen/Options.h
  include/scatha/CodeGen/Passes.h
  include/scatha/CodeGen/SelectionDAG.h
  include/scatha/CodeGen/SelectionNode.h

  include/scatha/Common/APMathFwd.h
  include/scatha/Common/APFloat.h
  include/scatha/Common/APInt.h
  include/scatha/Common/Allocator.h
  include/scatha/Common/Base.h
  include/scatha/Common/DebugMetadata.h
  include/scatha/Common/Dyncast.h
  include/scatha/Common/Expected.h
  include/scatha/Common/FFI.h
  include/scatha/Common/Graph.h
  include/scatha/Common/List.h
  include/scatha/Common/Logging.h
  include/scatha/Common/Metadata.h
  include/scatha/Common/Ranges.h
  include/scatha/Common/SourceFile.h
  include/scatha/Common/SourceLocation.h
  include/scatha/Common/UniquePtr.h
  include/scatha/Common/Utility.h

  include/scatha/IR/CFG/BasicBlock.h
  include/scatha/IR/CFG/Constant.h
  include/scatha/IR/CFG/Constants.h
  include/scatha/IR/CFG/Function.h
  include/scatha/IR/CFG/Global.h
  include/scatha/IR/CFG/GlobalVariable.h
  include/scatha/IR/CFG/Instruction.h
  include/scatha/IR/CFG/Instructions.h
  include/scatha/IR/CFG/Iterator.h
  include/scatha/IR/CFG/User.h
  include/scatha/IR/CFG/Value.h
  include/scatha/IR/CFG.h
  include/scatha/IR/Context.h
  include/scatha/IR/Fwd.h
  include/scatha/IR/Graphviz.h
  include/scatha/IR/IRParser.h
  include/scatha/IR/Lists.def.h
  include/scatha/IR/Module.h
  include/scatha/IR/Parser/IRIssue.h
  include/scatha/IR/Parser/IRSourceLocation.h
  include/scatha/IR/Parser/IRToken.h
  include/scatha/IR/Pass.h
  include/scatha/IR/PassManager.h
  include/scatha/IR/Pipeline.h
  include/scatha/IR/PipelineError.h
  include/scatha/IR/Print.h
  include/scatha/IR/UniqueName.h
  include/scatha/IR/ValueRef.h

  include/scatha/IRGen/IRGen.h

  include/scatha/Invocation/CompilerInvocation.h
  include/scatha/Invocation/ExecutableWriter.h
  include/scatha/Invocation/Target.h

  include/scatha/Issue/Issue.h
  include/scatha/Issue/IssueHandler.h
  include/scatha/Issue/IssueSeverity.h
  include/scatha/Issue/Message.h
  include/scatha/Issue/SourceStructure.h

  include/scatha/MIR/Context.h
  include/scatha/MIR/Fwd.h
  include/scatha/MIR/Lists.def.h
  include/scatha/MIR/Module.h
  include/scatha/MIR/Print.h

  include/scatha/Opt/SCCCallGraph.h
  include/scatha/Opt/Passes.h

  include/scatha/Parser/Lexer.h
  include/scatha/Parser/LexicalIssue.h
  include/scatha/Parser/Parser.h
  include/scatha/Parser/SyntaxIssue.h
  include/scatha/Parser/Token.def.h
  include/scatha/Parser/Token.h

  include/scatha/Sema/AnalysisResult.h
  include/scatha/Sema/Analyze.h
  include/scatha/Sema/Conversion.def.h
  include/scatha/Sema/Entity.h
  include/scatha/Sema/Fwd.h
  include/scatha/Sema/LifetimeMetadata.h
  include/scatha/Sema/LifetimeOperation.h
  include/scatha/Sema/Lists.def.h
  include/scatha/Sema/NameMangling.h
  include/scatha/Sema/Print.h
  include/scatha/Sema/QualType.h
  include/scatha/Sema/SemaIssues.def.h
  include/scatha/Sema/SemaIssues.h
  include/scatha/Sema/Serialize.h
  include/scatha/Sema/SymbolTable.h
  include/scatha/Sema/ThinExpr.h
  include/scatha/Sema/VTable.h
)

set(scatha_sources
    src/scatha/AST/AST.cc
    src/scatha/AST/AST.h
    src/scatha/AST/Fwd.cc
    src/scatha/AST/Print.cc
    src/scatha/AST/SpecifierList.h

    src/scatha/Assembly/AsmWriter.cc
    src/scatha/Assembly/AsmWriter.h
    src/scatha/Assembly/Assembler.cc
    src/scatha/Assembly/AssemblyStream.cc
    src/scatha/Assembly/Block.cc
    src/scatha/Assembly/Block.h
    src/scatha/Assembly/Common.cc
    src/scatha/Assembly/Common.h
    src/scatha/Assembly/Instruction.cc
    src/scatha/Assembly/Instruction.h
    src/scatha/Assembly/Linker.cc
    src/scatha/Assembly/Lists.def.h
    src/scatha/Assembly/Map.cc
    src/scatha/Assembly/Map.h
    src/scatha/Assembly/Print.cc
    src/scatha/Assembly/Print.h
    src/scatha/Assembly/Value.cc
    src/scatha/Assembly/Value.h

    src/scatha/CodeGen/CodeGen.cc
    src/scatha/CodeGen/CommonSubexpressionElimination.cc
    src/scatha/CodeGen/CopyCoalescing.cc
    src/scatha/CodeGen/DataFlow.cc
    src/scatha/CodeGen/DeadCodeElim.cc
    src/scatha/CodeGen/DestroySSA.cc
    src/scatha/CodeGen/ISel.cc
    src/scatha/CodeGen/ISel.h
    src/scatha/CodeGen/ISelCommon.cc
    src/scatha/CodeGen/ISelCommon.h
    src/scatha/CodeGen/InstSimplify.cc
    src/scatha/CodeGen/InterferenceGraph.cc
    src/scatha/CodeGen/InterferenceGraph.h
    src/scatha/CodeGen/JumpElision.cc
    src/scatha/CodeGen/Logger.cc
    src/scatha/CodeGen/LowerToASM.cc
    src/scatha/CodeGen/LowerToMIR.cc
    src/scatha/CodeGen/RegisterAllocator.cc
    src/scatha/CodeGen/Resolver.cc
    src/scatha/CodeGen/Resolver.h
    src/scatha/CodeGen/SDMatch.cc
    src/scatha/CodeGen/SDMatch.h
    src/scatha/CodeGen/SelectionDAG.cc
    src/scatha/CodeGen/SelectionNode.cc
    src/scatha/CodeGen/TargetInfo.cc
    src/scatha/CodeGen/TargetInfo.h
    src/scatha/CodeGen/Utility.cc
    src/scatha/CodeGen/Utility.h
    src/scatha/CodeGen/ValueMap.cc
    src/scatha/CodeGen/ValueMap.h

    src/scatha/Common/Allocator.cc
    src/scatha/Common/Base.cc
    src/scatha/Common/Builtin.cc
    src/scatha/Common/Builtin.h
    src/scatha/Common/DebugMetadata.cc
    src/scatha/Common/EscapeSequence.cc
    src/scatha/Common/EscapeSequence.h
    src/scatha/Common/FFI.cc
    src/scatha/Common/FileHandling.cc
    src/scatha/Common/FileHandling.h
    src/scatha/Common/Logging.cc
    src/scatha/Common/Metadata.cc
    src/scatha/Common/PrintUtil.cc
    src/scatha/Common/PrintUtil.h
    src/scatha/Common/SourceFile.cc
    src/scatha/Common/SourceLocation.cc
    src/scatha/Common/TreeFormatter.cc
    src/scatha/Common/TreeFormatter.h

    src/scatha/Debug/DebugGraphviz.cc
    src/scatha/Debug/DebugGraphviz.h

    src/scatha/IR/Attributes.h
    src/scatha/IR/Attributes.cc
    src/scatha/IR/BinSerialize.cc
    src/scatha/IR/BinSerialize.h
    src/scatha/IR/Builder.cc
    src/scatha/IR/Builder.h
    src/scatha/IR/CFG/BasicBlock.cc
    src/scatha/IR/CFG/Constant.cc
    src/scatha/IR/CFG/Constants.cc
    src/scatha/IR/CFG/Function.cc
    src/scatha/IR/CFG/Global.cc
    src/scatha/IR/CFG/GlobalVariable.cc
    src/scatha/IR/CFG/Instruction.cc
    src/scatha/IR/CFG/Instructions.cc
    src/scatha/IR/CFG/Iterator.cc
    src/scatha/IR/CFG/User.cc
    src/scatha/IR/CFG/Value.cc
    src/scatha/IR/Clone.cc
    src/scatha/IR/Clone.h
    src/scatha/IR/Context.cc
    src/scatha/IR/DataFlow.cc
    src/scatha/IR/DataFlow.h
    src/scatha/IR/Dominance.cc
    src/scatha/IR/Dominance.h
    src/scatha/IR/ForEach.cc
    src/scatha/IR/ForEach.h
    src/scatha/IR/Fwd.cc
    src/scatha/IR/Graphviz.cc
    src/scatha/IR/InvariantSetup.cc
    src/scatha/IR/InvariantSetup.h
    src/scatha/IR/Loop.cc
    src/scatha/IR/Loop.h
    src/scatha/IR/Module.cc
    src/scatha/IR/Parser/IRIssue.cc
    src/scatha/IR/Parser/IRLexer.cc
    src/scatha/IR/Parser/IRLexer.h
    src/scatha/IR/Parser/IRParser.cc
    src/scatha/IR/Pass.cc
    src/scatha/IR/PassManager.cc
    src/scatha/IR/PassRegistry.h
    src/scatha/IR/Pipeline.cc
    src/scatha/IR/PipelineError.cc
    src/scatha/IR/PipelineNodes.cc
    src/scatha/IR/PipelineNodes.h
    src/scatha/IR/PipelineParser.cc
    src/scatha/IR/PipelineParser.h
    src/scatha/IR/PointerInfo.cc
    src/scatha/IR/PointerInfo.h
    src/scatha/IR/Print.cc
    src/scatha/IR/Type.cc
    src/scatha/IR/Type.h
    src/scatha/IR/UniqueName.cc
    src/scatha/IR/Validate.cc
    src/scatha/IR/Validate.h
    src/scatha/IR/ValueRef.cc
    src/scatha/IR/VectorHash.h

    src/scatha/IRGen/CallingConvention.cc
    src/scatha/IRGen/CallingConvention.h
    src/scatha/IRGen/FuncGenContextBase.cc
    src/scatha/IRGen/FuncGenContextBase.h
    src/scatha/IRGen/FunctionGeneration.cc
    src/scatha/IRGen/FunctionGeneration.h
    src/scatha/IRGen/GlobalDecls.cc
    src/scatha/IRGen/GlobalDecls.h
    src/scatha/IRGen/IRGen.cc
    src/scatha/IRGen/LibImport.cc
    src/scatha/IRGen/LibImport.h
    src/scatha/IRGen/LoweringContext.h
    src/scatha/IRGen/Maps.cc
    src/scatha/IRGen/Maps.h
    src/scatha/IRGen/Metadata.cc
    src/scatha/IRGen/Metadata.h
    src/scatha/IRGen/Utility.cc
    src/scatha/IRGen/Utility.h
    src/scatha/IRGen/Value.cc
    src/scatha/IRGen/Value.h

    src/scatha/Invocation/CompilerInvocation.cc
    src/scatha/Invocation/ExecutableWriter.cc
    src/scatha/Invocation/Target.cc
    src/scatha/Invocation/TargetNames.h

    src/scatha/Issue/Format.cc
    src/scatha/Issue/Format.h
    src/scatha/Issue/Issue.cc
    src/scatha/Issue/IssueHandler.cc

    src/scatha/MIR/CFG.cc
    src/scatha/MIR/CFG.h
    src/scatha/MIR/Clone.cc
    src/scatha/MIR/Clone.h
    src/scatha/MIR/Context.cc
    src/scatha/MIR/Fwd.cc
    src/scatha/MIR/Hash.h
    src/scatha/MIR/Instruction.cc
    src/scatha/MIR/Instruction.h
    src/scatha/MIR/Instructions.cc
    src/scatha/MIR/Instructions.h
    src/scatha/MIR/LiveInterval.cc
    src/scatha/MIR/LiveInterval.h
    src/scatha/MIR/Module.cc
    src/scatha/MIR/Print.cc
    src/scatha/MIR/Register.cc
    src/scatha/MIR/Register.h
    src/scatha/MIR/RegisterSet.cc
    src/scatha/MIR/RegisterSet.h
    src/scatha/MIR/Value.cc
    src/scatha/MIR/Value.h

    src/scatha/Opt/AccessTree.cc
    src/scatha/Opt/AccessTree.h
    src/scatha/Opt/AllocaPromotion.cc
    src/scatha/Opt/AllocaPromotion.h
    src/scatha/Opt/Common.cc
    src/scatha/Opt/Common.h
    src/scatha/Opt/ConstantPropagation.cc
    src/scatha/Opt/DCE.cc
    src/scatha/Opt/DefaultPass.cc
    src/scatha/Opt/GlobalDCE.cc
    src/scatha/Opt/GlobalValueNumbering.cc
    src/scatha/Opt/HelloWorld.cc
    src/scatha/Opt/InlineCallsite.cc
    src/scatha/Opt/InlineCallsite.h
    src/scatha/Opt/InlineCost.cc
    src/scatha/Opt/InlineCost.h
    src/scatha/Opt/Inliner.cc
    src/scatha/Opt/InstCombine.cc
    src/scatha/Opt/InvariantPropagation.cc
    src/scatha/Opt/LoopPass.cc
    src/scatha/Opt/LoopRankView.cc
    src/scatha/Opt/LoopRankView.h
    src/scatha/Opt/LoopRotate.cc
    src/scatha/Opt/LoopUnroll.cc
    src/scatha/Opt/MemToReg.cc
    src/scatha/Opt/MemberTree.cc
    src/scatha/Opt/MemberTree.h
    src/scatha/Opt/Optimizer.cc
    src/scatha/Opt/PointerAnalysis.cc
    src/scatha/Opt/Rematerialize.cc
    src/scatha/Opt/ScalarEvolution.cc
    src/scatha/Opt/ScalarEvolution.h
    src/scatha/Opt/SCEV.def.h
    src/scatha/Opt/SCCCallGraph.cc
    src/scatha/Opt/SROA.cc
    src/scatha/Opt/SimplifyCFG.cc
    src/scatha/Opt/TailRecElim.cc
    src/scatha/Opt/UnifyReturns.cc

    src/scatha/Parser/Bracket.cc
    src/scatha/Parser/Bracket.h
    src/scatha/Parser/BracketCorrection.cc
    src/scatha/Parser/BracketCorrection.h
    src/scatha/Parser/Lexer.cc
    src/scatha/Parser/LexerUtil.cc
    src/scatha/Parser/LexerUtil.h
    src/scatha/Parser/LexicalIssue.cc
    src/scatha/Parser/Panic.cc
    src/scatha/Parser/Panic.h
    src/scatha/Parser/Parser.cc
    src/scatha/Parser/SyntaxIssue.cc
    src/scatha/Parser/Token.cc
    src/scatha/Parser/TokenStream.cc
    src/scatha/Parser/TokenStream.h

    src/scatha/Sema/Analysis/AnalysisContext.cc
    src/scatha/Sema/Analysis/AnalysisContext.h
    src/scatha/Sema/Analysis/Analyze.cc
    src/scatha/Sema/Analysis/ConstantExpressions.cc
    src/scatha/Sema/Analysis/ConstantExpressions.h
    src/scatha/Sema/Analysis/Conversion.cc
    src/scatha/Sema/Analysis/Conversion.h
    src/scatha/Sema/Analysis/ExpressionAnalysis.cc
    src/scatha/Sema/Analysis/ExpressionAnalysis.h
    src/scatha/Sema/Analysis/GatherNames.cc
    src/scatha/Sema/Analysis/GatherNames.h
    src/scatha/Sema/Analysis/Instantiation.cc
    src/scatha/Sema/Analysis/Instantiation.h
    src/scatha/Sema/Analysis/ProtocolConformance.cc
    src/scatha/Sema/Analysis/ProtocolConformance.h
    src/scatha/Sema/Analysis/OverloadResolution.cc
    src/scatha/Sema/Analysis/OverloadResolution.h
    src/scatha/Sema/Analysis/StatementAnalysis.cc
    src/scatha/Sema/Analysis/StatementAnalysis.h
    src/scatha/Sema/Analysis/StructDependencyGraph.cc
    src/scatha/Sema/Analysis/StructDependencyGraph.h
    src/scatha/Sema/Analysis/Utility.cc
    src/scatha/Sema/Analysis/Utility.h
    src/scatha/Sema/CleanupStack.h
    src/scatha/Sema/Entity.cc
    src/scatha/Sema/Format.cc
    src/scatha/Sema/Format.h
    src/scatha/Sema/Fwd.cc
    src/scatha/Sema/LifetimeFunctionAnalysis.cc
    src/scatha/Sema/LifetimeFunctionAnalysis.h
    src/scatha/Sema/LifetimeMetadata.cc
    src/scatha/Sema/NameMangling.cc
    src/scatha/Sema/Print.cc
    src/scatha/Sema/QualType.cc
    src/scatha/Sema/SemaIssues.cc
    src/scatha/Sema/Serialize.cc
    src/scatha/Sema/SerializeFields.def.h
    src/scatha/Sema/SymbolTable.cc
    src/scatha/Sema/ThinExpr.cc
    src/scatha/Sema/VTable.cc
)

set(scatha_test_sources
    test/scatha/Assembly/Assembler.t.cc

    test/scatha/CodeGen/DataFlow.t.cc

    test/scatha/Common/Allocator.t.cc
    test/scatha/Common/Expected.t.cc

    test/scatha/EndToEndTests/BitwiseOperations.t.cc
    test/scatha/EndToEndTests/BooleanOperations.t.cc
    test/scatha/EndToEndTests/Builtins.t.cc
    test/scatha/EndToEndTests/CodeGenerator.t.cc
    test/scatha/EndToEndTests/Conditions.t.cc
    test/scatha/EndToEndTests/Constructors.t.cc
    test/scatha/EndToEndTests/Conversion.t.cc
    test/scatha/EndToEndTests/DynamicCalls.t.cc
    test/scatha/EndToEndTests/GlobalVariables.t.cc
    test/scatha/EndToEndTests/Inlining.t.cc
    test/scatha/EndToEndTests/Library.t.cc
    test/scatha/EndToEndTests/LocalScopes.t.cc
    test/scatha/EndToEndTests/Loops.t.cc
    test/scatha/EndToEndTests/Math.t.cc
    test/scatha/EndToEndTests/MemberFunctions.t.cc
    test/scatha/EndToEndTests/Modules.t.cc
    test/scatha/EndToEndTests/Overloading.t.cc
    test/scatha/EndToEndTests/PassTesting.cc
    test/scatha/EndToEndTests/PassTesting.h
    test/scatha/EndToEndTests/References.t.cc
    test/scatha/EndToEndTests/Regression.t.cc
    test/scatha/EndToEndTests/SimpleRecursion.t.cc
    test/scatha/EndToEndTests/StaticData.t.cc
    test/scatha/EndToEndTests/Strings.t.cc
    test/scatha/EndToEndTests/Structures.t.cc

    test/scatha/Invocation/CompilerInvocation.t.cc

    test/scatha/IR/Clone.t.cc
    test/scatha/IR/DataFlow.t.cc
    test/scatha/IR/Dominance.t.cc
    test/scatha/IR/Equal.cc
    test/scatha/IR/Equal.h
    test/scatha/IR/EqualityTestHelper.cc
    test/scatha/IR/EqualityTestHelper.h
    test/scatha/IR/IR.t.cc
    test/scatha/IR/IRParser.t.cc
    test/scatha/IR/Iterator.t.cc
    test/scatha/IR/LoopNestingForest.t.cc
    test/scatha/IR/Types.t.cc
    test/scatha/IR/UniqueName.t.cc

    test/scatha/IRGen/Arrays.t.cc
    test/scatha/IRGen/ConditionalExpr.t.cc
    test/scatha/IRGen/ConversionExpr.t.cc
    test/scatha/IRGen/FunctionCalls.t.cc
    test/scatha/IRGen/MemberAccess.t.cc
    test/scatha/IRGen/ObjectConstruction.t.cc
    test/scatha/IRGen/ParameterGeneration.t.cc
    test/scatha/IRGen/Return.t.cc
    test/scatha/IRGen/Subscript.t.cc
    test/scatha/IRGen/UniquePtr.t.cc
    test/scatha/IRGen/Variables.t.cc

    test/scatha/Issue/Format.t.cc

    test/scatha/Lexer/Lexer.t.cc
    test/scatha/Lexer/LexerUtil.t.cc

    test/scatha/Main/Options.h
    test/scatha/Main/Main.cc

    test/scatha/Opt/Common.t.cc
    test/scatha/Opt/ConstantPropagation.t.cc
    test/scatha/Opt/GlobalValueNumbering.t.cc
    test/scatha/Opt/Inliner.t.cc
    test/scatha/Opt/InstCombine.t.cc
    test/scatha/Opt/LoopRotate.t.cc
    test/scatha/Opt/MemToReg.t.cc
    test/scatha/Opt/PassTest.cc
    test/scatha/Opt/PassTest.h
    test/scatha/Opt/PointerAnalysis.t.cc
    test/scatha/Opt/SROA.t.cc

    test/scatha/Parser/BracketCorrection.t.cc
    test/scatha/Parser/Parser.t.cc
    test/scatha/Parser/SimpleParser.cc
    test/scatha/Parser/SimpleParser.h
    test/scatha/Parser/SyntaxIssues.t.cc

    test/scatha/Sema/Conversion.t.cc
    test/scatha/Sema/FunctionNameCollision.t.cc
    test/scatha/Sema/FunctionSignature.t.cc
    test/scatha/Sema/Lifetime.t.cc
    test/scatha/Sema/NameMangling.t.cc
    test/scatha/Sema/OverloadResolution.t.cc
    test/scatha/Sema/OverloadSet.t.cc
    test/scatha/Sema/SemaUtil.cc
    test/scatha/Sema/SemaUtil.h
    test/scatha/Sema/SemanticAnalysis.t.cc
    test/scatha/Sema/SemanticErrors.t.cc
    test/scatha/Sema/SimpleAnalzyer.cc
    test/scatha/Sema/SimpleAnalzyer.h
    test/scatha/Sema/SymbolTable.t.cc
    test/scatha/Sema/SymbolTableSerialize.t.cc

    test/scatha/Util/CoutRerouter.cc
    test/scatha/Util/CoutRerouter.h
    test/scatha/Util/FrontendWrapper.cc
    test/scatha/Util/FrontendWrapper.h
    test/scatha/Util/IRTestUtils.cc
    test/scatha/Util/IRTestUtils.h
    test/scatha/Util/IssueHelper.cc
    test/scatha/Util/IssueHelper.h
    test/scatha/Util/LibUtil.cc
    test/scatha/Util/LibUtil.h
    test/scatha/Util/Set.h
)

set(scatha_benchmark_sources
  benchmark/scatha/Benchmark.cc
)
